# data.py 간단 분석
## build_y_vocab

In [2]:
import tqdm
import h5py  
from misc import get_logger, Option
opt = Option('./config.json')  

In [3]:
path = opt.train_data_list[0]
h = h5py.File(path, 'r')['train']


In [4]:
def get_class(h, i):
        b = h['bcateid'][i]
        m = h['mcateid'][i]
        s = h['scateid'][i]
        d = h['dcateid'][i]
        return '%s>%s>%s>%s' % (b, m, s, d)

In [5]:
y_vocab = {}

sz = 10#h['pid'].shape[0]

for i in tqdm.tqdm(range(sz), mininterval=1):
    class_name = get_class(h, i)
    if class_name not in y_vocab:
        y_vocab[class_name] = len(y_vocab)
y_vocab


100%|██████████| 10/10 [00:00<00:00, 818.30it/s]


{'10>9>11>-1': 4,
 '11>10>12>-1': 5,
 '11>15>17>-1': 9,
 '12>11>13>-1': 6,
 '13>12>14>-1': 7,
 '14>13>15>-1': 8,
 '1>1>2>-1': 0,
 '3>3>4>-1': 1,
 '5>5>6>-1': 2,
 '7>7>8>-1': 3}

In [6]:
y_vocab_1 = set()   
for k in y_vocab.keys():
    y_vocab_1.add(k)
    
y_vocab_2 = {y: idx for idx, y in enumerate(y_vocab_1)}

In [7]:
y_vocab_1

{'10>9>11>-1',
 '11>10>12>-1',
 '11>15>17>-1',
 '12>11>13>-1',
 '13>12>14>-1',
 '14>13>15>-1',
 '1>1>2>-1',
 '3>3>4>-1',
 '5>5>6>-1',
 '7>7>8>-1'}

In [8]:
y_vocab_2

{'10>9>11>-1': 4,
 '11>10>12>-1': 2,
 '11>15>17>-1': 6,
 '12>11>13>-1': 9,
 '13>12>14>-1': 5,
 '14>13>15>-1': 0,
 '1>1>2>-1': 1,
 '3>3>4>-1': 3,
 '5>5>6>-1': 8,
 '7>7>8>-1': 7}

- 위의 분석 결과를 보면 build_y_vocab 명령어는 계층구조의 타겟값을 하나의 클래스로 만들어주는 역할을 한다

## 데이터 셋 분석

In [9]:
import tqdm
import h5py  
from misc import get_logger, Option
opt = Option('./config.json')  

path = opt.train_data_list[0]
h = h5py.File(path, 'r')

In [10]:
print(dir(h))

['_MutableMapping__marker', '__abstractmethods__', '__bool__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_d', '_e', '_id', '_lapl', '_lcpl', 'attrs', 'clear', 'close', 'copy', 'create_dataset', 'create_group', 'driver', 'fid', 'file', 'filename', 'flush', 'get', 'id', 'items', 'keys', 'libver', 'mode', 'move', 'name', 'parent', 'pop', 'popitem', 'ref', 'regionref', 'require_dataset', 'require_group', 'setdefault', 'update', 'userblock_size', 'values', 'visit', 'visititems']


In [11]:
list(h.keys()) # h.keys()는 아마도 generater로 구성되었나보다?

['train']

In [12]:
list(h['train'].keys())

['bcateid',
 'brand',
 'dcateid',
 'img_feat',
 'maker',
 'mcateid',
 'model',
 'pid',
 'price',
 'product',
 'scateid',
 'updttm']

In [13]:
a = h['train']['model'][0]

In [14]:
a.decode() #유니코드 문자열을 일반 문자열로 변환

'퍼즐라이프 직소퍼즐 바다거북의 여행'

In [15]:

i = 0
print(h['train']['bcateid'][i],'             ',type(h['train']['bcateid'][i]))
print(h['train']['brand'][i].decode(),'     ',type(h['train']['brand'][i].decode()))
print(h['train']['dcateid'][i],'             ',type(h['train']['dcateid'][i]))
print(h['train']['img_feat'][i],'             ',type(h['train']['img_feat'][i]))
print(h['train']['maker'][i].decode(),'     ',type(h['train']['maker'][i].decode()))
print(h['train']['mcateid'][i],'             ',type(h['train']['mcateid'][i]))
print(h['train']['model'][i].decode(),'             ',type(h['train']['model'][i].decode()))
print(h['train']['pid'][i].decode(),'             ',type(h['train']['pid'][i].decode()))
print(h['train']['price'][i],'             ',type(h['train']['price'][i]))
print(h['train']['product'][i].decode(),'             ',type(h['train']['product'][i].decode()))
print(h['train']['scateid'][i],'             ',type(h['train']['scateid'][i]))
print(h['train']['updttm'][i].decode(),'             ',type(h['train']['updttm'][i].decode()))


1               <class 'numpy.int32'>
퍼즐라이프       <class 'str'>
-1               <class 'numpy.int32'>
[ 0.75723773  0.88493341  0.0776659  ...,  0.          1.02836633
  0.0683253 ]               <class 'numpy.ndarray'>
상품상세설명 참조       <class 'str'>
1               <class 'numpy.int32'>
퍼즐라이프 직소퍼즐 바다거북의 여행               <class 'str'>
O4486751463               <class 'str'>
16520               <class 'numpy.int32'>
직소퍼즐 - 1000조각 바다거북의 여행 (PL1275)               <class 'str'>
2               <class 'numpy.int32'>
20180227091029               <class 'str'>


In [16]:

def data_print(h,i = 0) : 
    
    print('{} : {}    {}'.format('상품정보업데이트시간',h['updttm'][i].decode(),type(h['updttm'][i].decode())))
    print('{} : {}    {}'.format('브랜드명',h['brand'][i].decode(),type(h['brand'][i].decode())))
    print('{} : {}    {}'.format('제조사',h['maker'][i].decode(),type(h['maker'][i].decode())))
    print('{} : {}    {}'.format('정제된 상품명',h['model'][i].decode(),type(h['model'][i].decode())))
    print('{} : {}    {}'.format('상품ID',h['pid'][i].decode(),type(h['pid'][i].decode())))
    print('{} : {}    {}'.format('상품명',h['product'][i].decode(),type(h['product'][i].decode())))
    print('{} : {}    {}'.format('가격',h['price'][i],type(h['price'][i])))
    print('\n')
    print('{} : {}    {}'.format('대카테고리ID',h['bcateid'][i],type(h['bcateid'][i])))
    print('{} : {}    {}'.format('중카테고리ID',h['mcateid'][i],type(h['mcateid'][i])))
    print('{} : {}    {}'.format('소카테고리ID',h['scateid'][i],type(h['scateid'][i])))
    print('{} : {}    {}'.format('세카테고리ID',h['dcateid'][i],type(h['dcateid'][i])))
    print('\n')
    print('{} : {}    {}'.format('ResNet50 feature',h['img_feat'][i],type(h['img_feat'][i])))
    print('------------------------------------------------------------')
for i in range(3) :   
    data_print(h['train'],i)      

상품정보업데이트시간 : 20180227091029    <class 'str'>
브랜드명 : 퍼즐라이프    <class 'str'>
제조사 : 상품상세설명 참조    <class 'str'>
정제된 상품명 : 퍼즐라이프 직소퍼즐 바다거북의 여행    <class 'str'>
상품ID : O4486751463    <class 'str'>
상품명 : 직소퍼즐 - 1000조각 바다거북의 여행 (PL1275)    <class 'str'>
가격 : 16520    <class 'numpy.int32'>


대카테고리ID : 1    <class 'numpy.int32'>
중카테고리ID : 1    <class 'numpy.int32'>
소카테고리ID : 2    <class 'numpy.int32'>
세카테고리ID : -1    <class 'numpy.int32'>


ResNet50 feature : [ 0.75723773  0.88493341  0.0776659  ...,  0.          1.02836633
  0.0683253 ]    <class 'numpy.ndarray'>
------------------------------------------------------------
상품정보업데이트시간 : 20180429085019    <class 'str'>
브랜드명 : 바보사랑    <class 'str'>
제조사 : MORY|해당없음    <class 'str'>
정제된 상품명 : 아이폰6S/6S+ tree farm101 - 다이어리케이스|아이폰6S/6S+    <class 'str'>
상품ID : P3307178849    <class 'str'>
상품명 : [모리케이스]아이폰6S/6S+ tree farm101 - 다이어리케이스[바보사랑][무료배송]    <class 'str'>
가격 : 20370    <class 'numpy.int32'>


대카테고리ID : 3    <class 'numpy.int32'>
중카테고리ID : 3    

 실제 학습에 사용될만한 입력 데이터는 많이 써야 아래 ~~4가지~~ 2가지 밖에 없다고 생각됨
 - ~~정제된 상품명(model) -> 중간에 순수 모델명(영어)가 있음 아니면 브랜드명과 같게 적은 것도 있음~~
 - 상품명(product)
 - ~~가격(price) -> 중간에 -1(입력 안된 상태가 있음)~~
 - ResNet50 feature(img_feat)
 
 분석결과 : 사람들이 기본정보 입력을 제대로 안 했다?

## make_db -전반부 : 'tmp/base.chunk.%s'까지 만드는 과정
- 궁금한점 : 만약 데이터가 100개씩 2set의 데이터가 있는데, 80개 단위로 chunk를 만들면 [80,20,60,40] 이렇게 4개의 chunk로 나누어 지는지 아니면 [80,80,40] 이렇게 3개의 chunk로 나누어 지는지 확인하자

In [17]:


def _split_data(data_path_list, div='train', chunk_size=2000):
        total = 0
        for data_path in data_path_list:
            h = h5py.File(data_path, 'r')
            sz = h[div]['pid'].shape[0]
            total += sz
        chunks = [(i, min(i + chunk_size, total)) for i in range(0, total, chunk_size)]
        return chunks

In [48]:
   
data_path_list = ['../../train.chunk.01','../../train.chunk.02']  
chunk_offsets = _split_data(data_path_list, div='train', chunk_size=200000)
num_chunks = len(chunk_offsets)
chunk_offsets, num_chunks


([(0, 200000),
  (200000, 400000),
  (400000, 600000),
  (600000, 800000),
  (800000, 1000000),
  (1000000, 1200000),
  (1200000, 1400000),
  (1400000, 1600000),
  (1600000, 1800000),
  (1800000, 2000000)],
 10)

In [19]:
tmp_chunk_tpl = 'tmp/base.chunk.%s'  
for cidx, (begin, end) in enumerate(chunk_offsets) :
    print(cidx,begin, end, tmp_chunk_tpl % cidx)

0 0 190000 tmp/base.chunk.0
1 190000 380000 tmp/base.chunk.1
2 380000 570000 tmp/base.chunk.2
3 570000 760000 tmp/base.chunk.3
4 760000 950000 tmp/base.chunk.4
5 950000 1140000 tmp/base.chunk.5
6 1140000 1330000 tmp/base.chunk.6
7 1330000 1520000 tmp/base.chunk.7
8 1520000 1710000 tmp/base.chunk.8
9 1710000 1900000 tmp/base.chunk.9
10 1900000 2000000 tmp/base.chunk.10


In [20]:
'tmp/base.chunk.%s'%2

'tmp/base.chunk.2'

In [21]:
h = h5py.File('../../train.chunk.01', 'r')
h['train/pid'][0],h['train']['pid'][0]

(b'O4486751463', b'O4486751463')

## make_db -중반부 : generate() ->  parse_data(label, h, i) 까지 과정

In [22]:
def get_class(h, i):
    b = h['bcateid'][i]
    m = h['mcateid'][i]
    s = h['scateid'][i]
    d = h['dcateid'][i]
    return '%s>%s>%s>%s' % (b, m, s, d)

def generate(data_path_list, begin_offset, end_offset, div='train'): #여기가 궁금한 부분임
        offset = 0
        for data_path in data_path_list:
            h = h5py.File(data_path, 'r')[div]
            sz = h['pid'].shape[0]
            if begin_offset and offset + sz < begin_offset:
                offset += sz
                continue
            if end_offset and end_offset < offset:
                break
            for i in range(sz):
                if not (begin_offset < offset + i <=end_offset):
                    continue
                class_name = get_class(h, i)
                yield h['pid'][i], class_name, h, i
            offset += sz

In [45]:
data_path_list = ['../../train.chunk.01','../../train.chunk.02']  

begin_offset, end_offset = 1000000, 1200000


tmp = generate(data_path_list, begin_offset, end_offset,'train') #pid, label, h, i /h는 원본 데이터 시작주소? i는 h의 인덱스


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [43]:
pid, label, h, i = next(tmp)
print(pid, label, h, i)

b'G3710875550' 3>3>38>8 <HDF5 group "/train" (12 members)> 1


### def parse_data(self, label, h, i)

In [25]:
from six.moves import cPickle 

y_vocab_path = './data/y_vocab.py3.cPickle'
y_vocab = cPickle.loads(open(y_vocab_path, 'rb').read())

In [26]:
y_vocab

{'36>412>2687>-1': 1123,
 '16>188>986>-1': 1869,
 '32>297>1397>-1': 1266,
 '23>322>1883>-1': 3954,
 '13>520>3106>-1': 3636,
 '12>172>265>-1': 492,
 '28>86>693>-1': 889,
 '37>178>778>-1': 3352,
 '53>465>2074>244': 3548,
 '51>403>2222>211': 2171,
 '2>66>685>169': 98,
 '13>12>1590>-1': 2572,
 '37>90>2303>-1': 1216,
 '10>9>1921>-1': 933,
 '14>40>284>-1': 291,
 '34>262>646>-1': 2021,
 '38>324>1248>-1': 1929,
 '56>503>2981>-1': 2840,
 '13>221>360>-1': 757,
 '24>200>866>-1': 1825,
 '10>457>2477>255': 3549,
 '2>66>685>76': 2644,
 '27>284>2438>-1': 1965,
 '2>23>-1>-1': 366,
 '37>349>949>-1': 446,
 '12>11>-1>-1': 3421,
 '40>183>1863>-1': 1823,
 '25>435>1834>-1': 801,
 '30>227>1573>-1': 3171,
 '34>439>2274>-1': 954,
 '9>233>-1>-1': 2999,
 '5>5>6>-1': 1786,
 '52>360>602>-1': 830,
 '10>236>2226>-1': 1204,
 '51>474>3101>-1': 2511,
 '10>427>2775>-1': 429,
 '13>361>1941>-1': 938,
 '13>257>503>-1': 969,
 '2>199>425>-1': 719,
 '56>504>2333>227': 1960,
 '52>451>-1>-1': 2825,
 '11>493>2418>246': 2912,
 '3

In [27]:
print(y_vocab.get('50>201>829>-1'), y_vocab['50>201>829>-1'])

281 281


In [28]:
import numpy as np
from keras.utils.np_utils import to_categorical

pid, label, h, i = next(tmp)
print('pid : {}, label : {}, h : {}, i : {}'.format(pid, label, h, i))
Y_ =y_vocab.get('50>201>829>-1')
Y = to_categorical(Y_, len(y_vocab))
print(Y.shape)

Using TensorFlow backend.


pid : b'G2149050275', label : 4>312>677>-1, h : <HDF5 group "/train" (12 members)>, i : 950002
(4068,)


In [29]:
# https://regexr.com
import re

#re_sc = re.compile('[\!@#$%\^&\*\(\)-=\[\]\{\}\.,/\?~\+\'"|]')   
re_sc = re.compile('[\!@#$%\^&\*\(\)\-=\[\]\{\}\.,/\?~\+\'"|]')   
#re_sc = re.compile('[)=]')   # 숫자가 없어지는 이유 : ')-=' 의미는 ')' to '=' 아스키코드 참고

In [30]:
product = h['product'][i].decode('utf-8')
product

'이노센트플러스 미엘J 슬라이딩 9자 장롱 NP10'

In [31]:
#product_ = re_sc.sub(' ', product).strip().split() #strip()은 공백 지우기
product_ = re_sc.sub(' ', product).split() #strip() 없어도 되는데.... 뭐징...
product_

['이노센트플러스', '미엘J', '슬라이딩', '9자', '장롱', 'NP10']

In [46]:
#words = [w.strip() for w in product_] # 이건 없어도 되는 것 같은데...
words=product_
print(words)

['이노센트플러스', '미엘J', '슬라이딩', '9자', '장롱', 'NP10']


In [33]:
words = [w for w in words if len(w) >= opt.min_word_length and len(w) < opt.max_word_length]

if not words: 
    print([None] * 2)
words

['이노센트플러스', '미엘J', '슬라이딩', '9자', '장롱', 'NP10']

In [34]:
import mmh3
hash_func = lambda x: mmh3.hash(x, seed=17) 

In [35]:
# 단어 -> hash값으로 변환
x = [hash_func(w) % opt.unigram_hash_size + 1 for w in words]
x

[82951, 72685, 54370, 66434, 47003, 34728]

In [36]:
from collections import Counter
xv_ = Counter(x) # key : hash값, value : 중복 숫자
xv_

Counter({34728: 1, 47003: 1, 54370: 1, 66434: 1, 72685: 1, 82951: 1})

In [37]:
xv = xv_.most_common(opt.max_len)# 이 테크닉은 기억하자!!!
xv

[(54370, 1), (82951, 1), (34728, 1), (47003, 1), (72685, 1), (66434, 1)]

In [38]:
x = np.zeros(opt.max_len, dtype=np.float32)
v = np.zeros(opt.max_len, dtype=np.int32)
for i in range(len(xv)):
    x[i] = xv[i][0]
    v[i] = xv[i][1]
X = (x,v)

In [39]:
Y, X

(array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 (array([ 54370.,  82951.,  34728.,  47003.,  72685.,  66434.,      0.,
              0.,      0.,      0.,      0.,      0.,      0.,      0.,
              0.,      0.,      0.,      0.,      0.,      0.,      0.,
              0.,      0.,      0.,      0.,      0.,      0.,      0.,
              0.,      0.,      0.,      0.], dtype=float32),
  array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)))

In [49]:
path = './tmp/base.chunk.5'
rets = cPickle.loads(open(path, 'rb').read())

In [58]:
pid, y, x = rets[1]
print('pid : ',pid)
print('y : ',y)
print('x : ',x)

pid :  b'O3422284709'
y :  [ 0.  0.  0. ...,  0.  0.  0.]
x :  (array([ 87478.,   7570.,  90666.,  49589.,   4586.,  88715.,  36874.,
        95647.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.], dtype=float32), array([2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))
